from typing import Any, Dict

# pylint: disable=all
# flake8: noqa

# TODO, add:
#  * https://old.reddit.com/r/wallstreetbets
#  * More RSS Feeds: https://rssbox.herokuapp.com/
#  * Note, for channel id for youtube influencer, please use rssbox above.
#  * Bitchute Feed thingy:
#    * https://greatawakening.win/p/HrTY9kpi/bitchute-rss-feeds-for-youtube-b/
BRIGHTEON = "brighteon"
YOUTUBE = "youtube"
RUMBLE = "rumble"
BITCHUTE = "bitchute"
SPREAKER = "spreaker"
ODYSEE = "odysee"
GAB = "gab"
SPOTIFY = "spotify"

# fmt: off
CHANNEL_LIBRARY = [
    #channel_name, source, channel_id
    ['Health Ranger Report',       BRIGHTEON,  'hrreport'                ],
    ['Sydney Watson',              YOUTUBE,    'UCSFy-1JrpZf0tFlRZfo-Rvw'],
    ['The Outer Light',            YOUTUBE,    'UCnrE7PkiyVPP5ZTMqo3QW-Q'],
    ['Ice Age Farmer',             YOUTUBE,    'UCI-Am0t4qQaP_Do9FwMWw3Q'],
    ['The Federalist',             RUMBLE,     'FDRLST'                  ],
    ['TimPool',                    YOUTUBE,    'UCG749Dj4V2fKa143f8sE60Q'],
    ['ThePeteSantilliShow',        RUMBLE,     'ThePeteSantilliShow'     ],
    ['Lex Fridman',                YOUTUBE,    'UCSHZKyawb77ixDdsGog4iWA'],
    ['PowerfulJRE',                YOUTUBE,    'UCzQUP1qoWDoEbmsQxvdjxgQ'],
    ['MouthyBuddha',               BITCHUTE,   'wnuZEpMvRZs6'            ],
    ['Computing Forever',          BITCHUTE,   'hybm74uihjkf'            ],
    ['Paul Joseph Watson',         YOUTUBE,    'UCittVh8imKanO_5KohzDbpg'],
    ['AwakenWithJP',               YOUTUBE,    'UCwUizOU8pPWXdXNniXypQEQ'],
    ['Thunderf00t',                YOUTUBE,    'UCmb8hO2ilV9vRa8cilis88A'],
    ['Wearechange',                YOUTUBE,    'UChwwoeOZ3EJPobW83dgQfAg'],
    ['Glennbeck',                  YOUTUBE,    'UCvqtzdcURSqNjY9RQEK4XmQ'],
    ['Stefan Molyneux',            BITCHUTE,   'freedomainradio'         ],
    ['StevenCrowder',              YOUTUBE,    'UCIveFvW-ARp_B_RckhweNJw'],
    ['Lauren Chen',                YOUTUBE,    'UCLUrVTVTA3PnUFpYvpfMcpg'],
    ['Rubin Report',               YOUTUBE,    'UCJdKr0Bgd_5saZYqLCa9mng'],
    ['Rebel Wisdom',               YOUTUBE,    'UCFQ6Gptuq-sLflbJ4YY3Umw'],
    ['Mark Dice',                  YOUTUBE,    'UCzUV5283-l5c0oKRtyenj6Q'],
    ['DeceptionBytes',             RUMBLE,     'DeceptionBytes'          ],
    ['RockingMrE',                 YOUTUBE,    'UCzOnXvfwc32YEiwTe_8Nf-g'],
    ['TheQuartering',              YOUTUBE,    'UCfwE_ODI1YTbdjkzuSi1Nag'],
    ['NextNewsNetwork',            YOUTUBE,    'UCLoNQH9RCndfUGOb2f7E1Ew'],
    ['The Jimmy Dore Show',        YOUTUBE,    'UC3M7l8ved_rYQ45AVzS0RGA'],
    ['Maryam Henein',              RUMBLE,     'c-699745'                ],
    ['RedPill78',                  RUMBLE,     'RedPill78'               ],
    ['SGTReport',                  BITCHUTE,   'nLPcg68RnP97'            ],
    ['James Allsup',               BITCHUTE,   'ku2nOmZ629lL'            ],
    ['Scott Adams',                YOUTUBE,    'UCfpnY5NnBl-8L7SvICuYkYQ'],
    ['Styxhexenhammer666',         YOUTUBE,    'UC0rZoXAD5lxgBHMsjrGwWWQ'],
    ['Timcast IRL',                YOUTUBE,    'UCLwNTXWEjVd2qIHLcXxQWxA'],
    ['AmazingPolly',               BITCHUTE,   'ZofFQQoDoqYT'            ],
    ['The Epoch Times News',       YOUTUBE,    'UCeLc4heXqG9dtL7jiPHMBfQ'],
    ['JordanSather',               BITCHUTE,   'XyIkC2xqtFHY'            ],
    ['EdgeofWonder',               RUMBLE,     'EdgeofWonder'            ],
    ['MrReagan',                   YOUTUBE,    'UCf1EWeQ7DefD6Ds3KdeQ-uQ'],
    ['SarahWestall',               BITCHUTE,   '1Ez5eVnVz1yY'            ],
    ['MillieWeaver',               YOUTUBE,    'UCglVbeKF9JGMCt-RTUAW_TQ'],
    ['NTD',                        YOUTUBE,    'UC8Ioh4atNDO5a0Vy2qFmauQ'],
    ['JustTheNews',                RUMBLE,     'JustTheNews'             ],
    ['DineshDsouza',               RUMBLE,    'DineshDsouza'             ],
    ['VoxDay',                     YOUTUBE,    'UCGJNdaSwFeP3pLd1MhN0dRg'],
    ['The Last American Vagabond', BITCHUTE,   '24yVcta8zEjY'            ],
    ["Brendon O'Connel",           YOUTUBE,  'UCDtDeNQhWST7EnDtx-DSfug'  ],  # Alt channel
    ['RSBN',                       YOUTUBE,    'UCHqC-yWZ1kri4YzwRSt6RGQ'],
    ['FoxNews',                    YOUTUBE,    'UCXIJgqnII2ZOINSWNOGFThA'],
    ['OANN',                       RUMBLE,     'OANN'                    ],
    ['MarkLevinShow',              RUMBLE,     'MarkLevinShow'           ],
    ['corbettreport',              BITCHUTE,   'GwPziiQZrVT3'            ],
    ['RichieFromBoston',           BITCHUTE,   'juH53r3AyWVW'            ],
    ['Dave Janda',                 YOUTUBE,    'UCJ-qLG1bdWVrHM-Hu2W73CQ'],
    ['Crossroads',                 YOUTUBE,    'UCG8yy4W8nBbTle9YSpCqXeg'],
    ['Thomas Wictor',              YOUTUBE,    'UCifzRVl4nx5dZOYiuM7Q2HQ'],
    ['Ann Vandersteel | Steel Truth Medial', RUMBLE, 'SteelTruth'        ],
    ['VALUETAINMENT',              YOUTUBE,    'UCIHdDJ0tjn_3j-FS7s_X1kQ'],
    ['American Thought Leaders',   YOUTUBE,    'UCmWhuFRkZKu0g-e1xrlakVA'],
    ['The Stoa',                   YOUTUBE,    'UCfI5jzpoUbwP4wkmQ6ZNqbA'],
    ['An0maly',                    YOUTUBE,    'UC4vptswS-qIpvz0NiocrGsA'],
    ['PragerUniversity',           YOUTUBE,    'UCZWlSUNDvCCS1hBiXV0zKcA'],
    ['Tracy Beanz',                YOUTUBE,    'UC98Zwfvjq12M1oi99Yqd78w'],
    ['Black Pigeon Speaks',        YOUTUBE,    'UCmrLCXSDScliR7q8AxxjvXg'],
    ['Liberty Hangout',            YOUTUBE,    'UCQMb7c66tJ7Si8IrWHOgAPg'],
    ['Black Pilled',               YOUTUBE,    'UCvaHgYcWAAcn5D54w4Dqezg'],
    ['Quite Frankly',              YOUTUBE,    'UCtB5nbKHYsX8EGIk9cOevaQ'],
    ['The Truth About Cancer',     RUMBLE,     'TheTruthAboutCancerOfficial'],
    ['Sean Hannity',               RUMBLE,     'SeanHannity'             ],
    ['Infowars',                   BITCHUTE,   "9c7qJvwx7YQT"            ],
    ['Infowars Warroom',           BITCHUTE,   "9c7qJvwx7YQ1"            ],
    ['JustInformed Talk',          BITCHUTE,   'zWqrqKTLkhqW'            ],
    ['Dustin Nemos',               BITCHUTE,   'QKL2mVYPDV5u'            ],
    ['InPursuitOfTruth',           BITCHUTE,   'Xe2ztraIRXRX'            ],
    ['Stroppy',                    BITCHUTE,   'M4YtazGIdcIH'            ],
    ['IntheMatrixxx',              BITCHUTE,   'LYlGuC0RYchh'            ],
    ['DiamondandSilk',             RUMBLE,     'DiamondandSilk'          ],
    ['Alen Dershowitz',            RUMBLE,     'Dershow'                 ],
    ['Lara Trump',                 RUMBLE,     'LaraTrump'               ],
    ['Mr Obvious',                 YOUTUBE,    'UCyznn3etx_6fSK7576JSrKg'],
    ['Charlie Kirk',               YOUTUBE,    'UCfaIu2jO-fppCQV_lchCRIQ'],
    ['Stew Peters',                RUMBLE,     'StewPeters'              ],
    ["Doug Billings",              RUMBLE,     'DougBillings'            ],
    ['Theo Von',                   YOUTUBE,    'UC5AQEUAwCh1sGDvkQtkDWUQ'],
    ['Ryan Long',                  YOUTUBE,    'UCzKFvBRI6VT3jYJq6a820nA'],
    ['Matt Christiansen',          YOUTUBE,    'UCxeY-wRrb65Jt37QHa5xMog'],
    ['Anthony Brian Logan',        YOUTUBE,    'UCu8ebUHoKbhVY0tavNdhwvw'],
    ['Jordan B Peterson',          YOUTUBE,    'UCL_f53ZEJxp8TtlOkHwMV9Q'],
    ['Jack Murphey Live',          YOUTUBE,    'UCJZYQRyRNZ1K0HxtT-6t9bA'],
    ['Robert Gruler',              YOUTUBE,    'UCQa62kyOcsyhVUqyvRCbDNQ'],
    ["Corey's Digs",               RUMBLE,     'CoreysDigs'              ],
    ['Bill Maher',                 YOUTUBE,    'UCy6kyFxaMqGtpE3pQTflK8A'],
    ['Chrissie Mayr',              YOUTUBE,    'UCqthtsHZXxGKIVa_mFw9awA'],
    ['Project Veritas',            YOUTUBE,    'UCL9PlYkRD3Q-RZca6CCnPKw'],
    ['The Savvy Truth',            RUMBLE,     'TheSavvyTruth'           ],
    ['The John-Henry Westen Show', YOUTUBE,    'UCTLd2bFGKP043ycgahPxi5A'],
    ['NewsmaxTV',                  YOUTUBE,    'UCx6h-dWzJ5NpAlja1YsApdg'],
    ['AdamcastIRL',                YOUTUBE,    'UCCNLO0GPt_8zB3hcbFEcDog'],
    ['Gateway Pundit',             RUMBLE,     'TheGatewayPundit'        ],
    ['The Tech Lead Show',         YOUTUBE,    'UC_us_hH43AJtU_A-iXCLmqw'],
    ['Tim Dillon Show Clips',      YOUTUBE,    'UCTDMN4NwdZ0VVbvvjTTSqpA'],
    ['Tim Dillon Show',            YOUTUBE,    'UC4woSp8ITBoYDmjkukhEhxg'],
    ['The Truth Factory',          YOUTUBE,    'UC2aQGaCZjQC1lM3DOwbCIFw'],
    ['Spiro Skouras',              BITCHUTE,   'IiUMdsNGJBE2'            ],
    ['Brietbart News',             YOUTUBE,    'UCmgnsaQIK1IR808Ebde-ssA'],
    ['Candace Owens',              YOUTUBE,    'UCL0u5uz7KZ9q-pe-VC8TY-w'],
    ['Armored Skeptic',            YOUTUBE,    'UC1BWMtZbNLVMSFgwSukjqCw'],
    ['Black Conservative Patriot', YOUTUBE,    'UCdVSlmNi1uyfsgOAT_TbVyg'],
    ['Tim Ferriss',                YOUTUBE,    'UCznv7Vf9nBdJYvBagFdAHWw'],
    ['1791',                       YOUTUBE,    'UCp4oMaqaY0hIoT9jafj1g8g'],
    ["Chris D'Elia",               YOUTUBE,    'UCTeIxzkL9QZ2noyLVUNfXJg'],
    ['Bishop Larry Gaiters',       YOUTUBE,    'UC3JVrMzi2PGAqnbdKgq4BuQ'],
    ['Joe Scott',                  YOUTUBE,    'UC-2YHgc363EdcusLIBbgxzg'],
    ['Senator Ted Cruz',           YOUTUBE,    'UCOTZ-6H1rri1lSsj6IzhUyw'],
    ['The School of Life',         YOUTUBE,    'UC7IcJI8PUf5Z3zKxnZvTBog'],
    ['Matt Couch',                 RUMBLE,     'SomethingDifferentwithMattCouch'        ],
    ['Press For Truth',            YOUTUBE,    'UCMOWB-s0Kek9o9sS8xA_kZQ'],
    ['Fleccas Talks',              YOUTUBE,    'UCIpwPuJsrboNnf200oV8cWQ'],
    ['Dr Rashid A Buttar',         BITCHUTE,   'gHlmvogFIA1k'            ],
    ['Andy Ngo',                   YOUTUBE,    'UCmmfVSRVwMSfHdRf6v3lPxQ'],
    ['The Christopher Wright Show',YOUTUBE,    'UC_ElOANq_1BwPNFWmWHXtzw'],
    ["Other People's Lives",       YOUTUBE,    'UC5TgU2fZc5x3DqdspqqtlsA'],
    ['Whitney Cummings',           YOUTUBE,    'UCZa3lYPi8caXYxl5DeIzJgg'],
    ['The Art of Improvement',     YOUTUBE,    'UCtYzVCmNxrshH4_bPO_-Y-A'],
    ['Charisma on Command',        YOUTUBE,    'UCU_W0oE_ock8bWKjALiGs8Q'],
    ['NTDChinaUncensored',         YOUTUBE,    'UCgFP46yVT-GG4o1TgXn-04Q'],
    ['ADVChina',                   YOUTUBE,    'UCwNPa8fSXzzAZuT9859GVhg'],
    ['serpentza',                  YOUTUBE,    'UCl7mAGnY4jh4Ps8rhhh8XZg'],
    ['laowhy86',                   YOUTUBE,    'UChvithwOECK5g_19TjldMKw'],
    ['China Unscripted',           YOUTUBE,    'UCvr1DclUsRzNYXWOWJ7eVLQ'],
    ['America Uncovered',          YOUTUBE,    'UC_7vFlErTHxVD-IFNB-BFCg'],
    ['Akkad Daily',                YOUTUBE,    'UCitU2-w3XE8ujvUZjcAnhIg'],
    ['Memology 101',               YOUTUBE,    'UC1X9HTMhyL4UpmjgkrN41oQ'],
    # Crypto channels.
    ['Lark Davis',                 YOUTUBE,    'UCl2oCaw8hdR_kbqyqd2klIA'],
    ['Hashoshi',                   YOUTUBE,    'UCQNHKsYDGlWefzv9MAaOJGA'],
    ['Coin Bureau',                YOUTUBE,    'UCqK_GSMbpiV8spgD3ZGloSw'],
    ['Digital Asset News',         YOUTUBE,    'UCJgHxpqfhWEEjYH9cLXqhIQ'],
    ['Dapp University',            YOUTUBE,    'UCY0xL8V6NzzFcwzHCgB8orQ'], 
    ['DataDash',                   YOUTUBE,    'UCCatR7nWbYrkVXdxXb4cGXw'],
    ['Sheldon Evans',              YOUTUBE,    'UCZ3fejCy_P5xhv9QF-V6-YA'],
    ['Alex Becker',                YOUTUBE,    'UCKQvGU-qtjEthINeViNbn6A'],
    ['JRNY Crypto',                YOUTUBE,    'UC188KLMYLLGqVJZdYq7mYFw'],
    ['Benjamin Cowen',             YOUTUBE,    'UCRvqjQPSeaWn-uEx-w0XOIg'],
    ['Preston Pysh',               YOUTUBE,    'UCLTdCY-fNXc1GqzIuflK-OQ'],
    ['Bankless',                   YOUTUBE,    'UCAl9Ld79qaZxp9JzEOwd3aA'],
    ['PatrickByrne',               RUMBLE,     'PatrickByrne'            ],
    ['PatriotStreetfighter',       RUMBLE,     'PatriotStreetfighter'    ],
    ['Creel',                      YOUTUBE,    'UCq7dxy_qYNEBcHqQVCbc20w'],
    ['Dr. Eric Berg',              YOUTUBE,    'UC3w193M5tYPJqF0Hi-7U-2g'],
    ['Jerry Brainum',              YOUTUBE,    'UCy3X58lwho_w1DsIgV7V7xg'],
    ['Dr. Philip Oubre, MD',       YOUTUBE,    'UCvGAY-5kSoCxahkDoeCJRfA'],
    ['Dr Brad Stanfield',          YOUTUBE,    'UCpcvPcHJVOkO9Qp79BOagTg'],
    ['Ford Brewer MD MPH',         YOUTUBE,    'UCmoEsq6a6ePXxgZeA4CVrUw'],
    ['Dr. Rhonda Patrick',         YOUTUBE,    'UCWF8SqJVNlx-ctXbLswcTcA'],
    ['Dr. Mark Hyman, MD',         YOUTUBE,    'UC5IuDMmKWSsBFB0iKky6aEQ'],
    ['The Highwire with Dell Big Tree', RUMBLE,'c-356275'                ],
    ['Dr Sherri Tenpenny',         RUMBLE,     'c-593647'                ],
    ['Crypto Banter',              YOUTUBE,    'UCN9Nj4tjXbVTLYWN0EKly_Q'],
    ['Altcoin Daily',              YOUTUBE,    'UCbLhGKVY-bJPcawebgtNfbw'],
    ['BitBoy Crypto',              YOUTUBE,    'UCjemQfjaXAzA-95RKoy9n_g'],
    ['Ryan Dawson',                BITCHUTE,   'kCBxN1oEVOa0'            ],
    ['Sargon of Akkad',            YOUTUBE,    'UC-yewGHQbNFpDrGM0diZOLA'],
    ['Lauren Southern',            YOUTUBE,    'UCla6APLHX6W3FeNLc8PYuvg'],
    ['Russell Brand',              YOUTUBE,    'UCswH8ovgUp5Bdg-0_JTYFNw'],
    ['99Bitcoins',                 YOUTUBE,    'UCQQ_fGcMDxlKre3SEqEWrLA'],
    ['Crypto Dad',                 YOUTUBE,    'UCS8RlHFegeN4yrDW6jPSYuQ'],
    ['Dollar Vigilante',           BITCHUTE,   'DkNYbFJKDPpX'            ],
    ['Judicial Watch',             YOUTUBE,    'UCGDaOZg2INC0Qg2Z203F1dA'],
    ['WhatsHerFace',               YOUTUBE,    'UCMZjeadL0c2PSix1Gr7mqKw'],
    ['FreedomToons',               YOUTUBE,    'UCRXnOs1rjfLMYrtZ-0n29NA'],
    ['Common Sense Soapbox',       YOUTUBE,    'UCRP7zAaW64tGw26Ee2h-l-Q'],
    ['The Salty Cracker',          BITCHUTE,   's7sIruG9mgWl'            ],
    ['Journey to Truth',           YOUTUBE,    'UCRRvPkqEdeu2Pjd52qfXTlA'],
    ['Sara Carter',                YOUTUBE,    'UC_x1RxL7HFnKyC0czqGfBug'],
    ["Real America's Voice",       YOUTUBE,    'UCMGZ8pfQHgZ6Yj0-92PMENg'],
    ['Rebel News',                 YOUTUBE,    'UCGy6uV7yqGWDeUWTZzT3ZEg'],
    ['The Solari Report',          YOUTUBE,    'UC8Vq8rpqluEF07NSt9ipCkQ'],
    ['Dr. Steve Turley',           YOUTUBE,    'UCCsiAKRKcgzA_372WbXNBaw'],
    ['SCNR',                       YOUTUBE,    'UCLMSv1UJp9sfoHyo-9s6sdw'],
    ['HighImpactFlix',             BITCHUTE,   'highimpactflix'          ],
    ['Lisa Haven',                 YOUTUBE,    'UCBDrbqudUtPUQxAK_K2JaNQ'],
    ['The Conscious Resistance Network', BITCHUTE, 'v4jgxgSNfpCX'        ],
    ['Rudy W. Guiliani',           YOUTUBE,    'UC-9J07yyuXQTx_uZQchtwsg'],
    ['Really Graceful',            YOUTUBE,    'UCY-UU3bN4FkMILC-CMd8N5w'],
    ['The Crowhouse',              BITCHUTE,   'tj99AwcN3zlH'            ],
    ['Lionel Nation',              YOUTUBE,    'UCa3-BNaCeCvGSfhMuotYskg'],
    ['CitizensInvestigativeReport', BITCHUTE,  '9J9QUFu3D8rS'            ],
    ['Truthstream Media',          YOUTUBE,    'UCVEaFSr-jdTa_QE4PPSkVJw'],
    ['Caravan to Midnight',        YOUTUBE,    'UCuHJMn2CfyxMPGPzFww_3bA'],
    ['Sam Tripoli',                YOUTUBE,    'UCBgldhBkwIxoQp0fxBg8pgA'],
    ['Craig Mason',                BITCHUTE,   'aSnzQyGMuvod'            ],
    ['Dan Bongino',                RUMBLE,     'Bongino'                 ],
    ['Natly Denise',               YOUTUBE,    'UCXqqnMguDZ7vhB73xM7uR0Q'],
    ['Declassified with Gina Shakespeare', YOUTUBE, 'UCw14RqKlnGoxHPHmqO9LxEQ'],
    ['Earthfiles',                 YOUTUBE,    'UCN9WjlKBvjBIm3AWDXI1EUA'],
    ['RichardMDolan',              YOUTUBE,    'UCnaIeNm-jSa1l8yHrn7PlQg'],
    ['Slightly Offens*ve',         YOUTUBE,    'UCMRxoFJPZiBcxgFzxN0ao-w'],
    ['Dr. David Jockers',          YOUTUBE,    'UCIAZtlZSFlnBp_hAlvB6QSw'],
    ['I,Hypocrite',                YOUTUBE,    'UCKGLZ1K7jKfi_42bHxdCBrA'],
    ['Matt Walsh',                 YOUTUBE,    'UCO01ytfzgXYy4glnPJm4PPQ'],
    ['CDMedia',                    RUMBLE,     'CDMedia'                 ],
    ['Man In America',             YOUTUBE,    'UCWYpdDqpiqWJR63qvFdMTGQ'],
    ['ODD TV',                     YOUTUBE,    'UCuftdXePz6z73Wsg8Ao5lTg'],
    ['Bret Weinstein',             ODYSEE,     'BretWeinstein'           ],
    ['Behizy',                     ODYSEE,     'Behizy'                  ],
    ['BannonsWarRoom',             RUMBLE,     'BannonsWarRoom'          ],
    ['Jovan Hutton Pulitzer',      RUMBLE,     'c-1037371'               ],
    ["Children's Health Defense",  RUMBLE,     'childrenshealthdefense'  ],
    ['Donald Trump',               RUMBLE,     'DonaldTrump'             ],
    ['Gothix',                     YOUTUBE,    'UC0UoMX5ed9Ax_up8lkM0N0g'],
    ['KanekoaTheGreat',            RUMBLE,     'KanekoaTheGreat'         ],
    ['MotivationalDoc',            YOUTUBE,    'UCKcWSiffY8MpZ3NKav8LeRA'],
    ['The John Birch Society',     YOUTUBE,    'UCD_PvRz7fvX9WOBL6T4P45Q'],
    ['Thomas DeLauer',             YOUTUBE,    'UC70SrI3VkT1MXALRtf0pcHg'],
    ['Pete Santilli Interviews',   RUMBLE,     'PeteSantilliInterviews'  ],
    ['April Moss',                 RUMBLE,     'c-1081514'               ],
    ['Roosh V',                    BITCHUTE,   'tPPHz1npTCgk'            ],
    ['After Skool',                YOUTUBE,    'UC1KmNKYC1l0stjctkGswl6g'],
    ['Academy of Ideas',           YOUTUBE,    'UCiRiQGCHGjDLT9FQXFW0I3A'],
    ['Glen Greenwald',             RUMBLE,     'GGreenwald'              ],
    ['Dr. John Campbel',           YOUTUBE,    'UCF9IOB2TExg3QIBupFtBDxg'],
    ['Dr. Paul Thomas Md',         YOUTUBE,    'UC6uLAeupunADT4mhv_c_epQ'],
    ['Robert Scott Bell',          RUMBLE,     'RSBellMedia'             ],
    ['Viva Frei',                  YOUTUBE,    'UCzGiDDKdphJ0GFvEd82WfYQ'],
    ['Nicholas Veniamin',          BITCHUTE,   'jcOs2EA1BUJH'            ],
    ['Alpa Soni',                  YOUTUBE,    'UCeTRiTsNoUqMl6cuhm63QDA'],
    ['Joe Rogan',                  SPOTIFY,    '4rOoJ6Egrf8K2IrywzwOMk'  ],
    ['Dana Loesch',                YOUTUBE,    'UCMgU2c86gIV4s408gNwl-hQ'],
    ['Dr. Mercola',                RUMBLE,     'Mercola'                 ],
    ['Dr. Darren Schmidt, DC',     YOUTUBE,    'UC_XAkQmLOnNrWRC4rckr1wg'],
    ['Ben Shapiro',                YOUTUBE,    'UCnQC_G5Xsjhp9fEJKuIcrSw'],
    ['Michael Knowles',            YOUTUBE,    'UCr4kgAUTFkGIwlWSodg43QA'],
    ['Mel K Show',                 RUMBLE,     'TheMelKShow'             ],
    ['Philip DeFranco',            YOUTUBE,    'UClFSU9_bUb4Rc6OYfTt5SPw'],
    ['Breaking Points',            YOUTUBE,    'UCDRIjKy6eZOvKtOELtTdeUA'],
    ['George Galloway',            YOUTUBE,    'UCf_HItERkRB3vnkWt2RSOLg'],
    ['Kim Iverson',                YOUTUBE,    'UCoJTOwZxbvq8Al8Qat2zgTA'],
    ['Gavin McInnes',              BITCHUTE,   'wQM1mHJYYezz'            ],
    ['Monica Matthews',            YOUTUBE,    'UCgdOEYK4G9Ku6nXJtxahdvg'],
    ['JD Rucker Show',             RUMBLE,     'JDRuckerShow'            ],
    ['Rekieta Law',                YOUTUBE,    'UCbkjX3E0IhuUfPzL0FjSPaw'], 
    ['Woke Societies',             RUMBLE,     'WokeSocieties'           ],
    ['Citizen Media News',         YOUTUBE,    'UCNWaeBhhFcZVQE2UqQsMXsA'],
    ['Red Voice Media',            RUMBLE,     'RedVoiceMedia'           ],
    ['TRUreporting',               RUMBLE,     'TRUreporting'            ],
    ['Clif High',                  BITCHUTE,   'HBBwqdoMy7Gz'            ],
    ['The Alpha Warrior Show',     RUMBLE,     'TheAlphaWarriorShow'     ],
    ['Ivory Hecker',               YOUTUBE,    'UCr4iMJDCSdzkfgmXHVpX9Rw'],
    ['Nick Moseder',               RUMBLE,     'NickMoseder'             ],
    ['Neil Johnson',               YOUTUBE,    'UCsPefdHXI74iqgvaUo0L4bg'],
    ['Cooper Stuff',               YOUTUBE,    'UCVyns6BCG0OtS_n5Vqjg-sA'],
    ['Sarah Corriher',             YOUTUBE,    'UClFE0KTVxyOB7lpZ-JdD1Rw'],
    ['Jeremy Herrell',             RUMBLE,     'LFATV'                   ],
    ['Jeff Dornik Show',           RUMBLE,     'TheJeffDornikShow'       ],
    ['Two Mikes',                  RUMBLE,     'TwoMikes'                ],
    ['On The Fringe',              RUMBLE,     'OnTheFringe'             ],
    ['And We Know',                RUMBLE,     'AndWeKnow'               ],
    ['Mr Truth Bomb',              BITCHUTE,   'MrTruthBomb'             ],
    ['Conservative Daily',         RUMBLE,     'ConservativeDaily'       ],
    ['The Ripple Effect',          ODYSEE,     'therippleeffectpodcast'  ],
    ['America Floats',             ODYSEE,     'AmericaFloats'           ],
    ['Monkey Werx',                YOUTUBE,    'UCUmvAVqbS-_5feqZPHA99Lw'],
    ['Medical Medium',             YOUTUBE,    'UCUORv_qpgmg8N5plVqlYjXg'],
    ['Dnajlion7',                  RUMBLE,     'Dnajlion7'               ],
    ['Godspeak',                   RUMBLE,     'Godspeak'                ],
    ['Full Disclosure',            RUMBLE,     'fulldisclosure'          ],
    ['King Peter the Virile',      YOUTUBE,    'UC-6jX5eJtrrL8aI8Fv7n63w'],
    ['Sean Morgan Report',         RUMBLE,     'SeanMorganReport'        ],
    ['The United Spot',            YOUTUBE,    'UCWj9zYsPkotQFSJNK4g4vnQ'],
    ['Dr. Sten Ekberg',            YOUTUBE,    'UCIe2pR6PE0dae9BunJ38F7w'],
    ["Kevin's Corner",             YOUTUBE,    'UCEMnbZhWrFqp_LzBxei60cA'],
    ["Richard Grove",              YOUTUBE,    "UCnYKjBrI1ErwhDprla7Unwg"],
    ["Thrivetime Show",            RUMBLE,     "ThrivetimeShow"          ],
    ["JSlayUSA",                   RUMBLE,     "c-719485"                ],
    ["Lawyers' Committee for 9/11 Inquiry", YOUTUBE, "UCWQbEeExutR4vR4pEFmQUJw"],
    ["American Media Periscope",   RUMBLE,     "AmericanMediaPeriscope"  ],
    ["Patrick Lancaster",          YOUTUBE,    "UCbjTWVaRx6jMN5ZYgbqe2_w"],
    ["Peak Prosperity",            YOUTUBE,    "UCD2-QVBQi48RRQTD4Jhxu8w"],
    ["Liberal Hivemind",           YOUTUBE,    "UCIr4vkCsn0tdTW2xZ1jRG1g"],
    ["Macroaggressions",           ODYSEE,     "Macroaggressions"        ],
    ["Canadian Prepper",           YOUTUBE,    "UCfgtuaUadGgOA-91geQ8Qog"],
    ["Matt Gaetz",                 RUMBLE,     "RepMattGaetz"            ],
    ["Sivaady",                    RUMBLE,     "sivaady"                 ],
    ["Brittany Venti",             YOUTUBE,    "UCLGRZ0xSaBMIUmtn8wkPP3w"],
    ["RED PILL PORTAL",            BITCHUTE,   "mgch3U4zv1lF"            ],
    ["Ganzalo Lira",               YOUTUBE,    "UCfUzUq5L9NFv2GMVGbEBgkg"],
    ["Union of the Unwanted",      ODYSEE,     "uotuw:e"                 ],
    ["BraveTV",                    RUMBLE,     "BraveTV"                 ],
    ["Jason Bermas",               RUMBLE,     "TheInfoWarrior"          ],
    ["Isaac Smith",                YOUTUBE,    "UCj4renCkNCt4wY89BMdwoaw"],
    ["Titus Smith",                YOUTUBE,    "UC_EyZ7IiQLFYpsipHVXUmgg"],
    ["Jim Breuer",                 RUMBLE,     "JimBreuer"     ],
    ["Project Veritas Action",     YOUTUBE,    "UCEE8w-v6Gg4j3ze3oX-urEw"],
    ["AlisonMorrow",               RUMBLE,     "AlisonMorrow"            ],
    ["Know More News",             BITCHUTE,   "qPYBk4x8LaDs"            ],
    ["Conversations That Matter",  RUMBLE,     "ConversationsThatMatterTNA"],
    ["The Real News Network",      YOUTUBE,    "UCrmm_7RDZJeQzq2-wvmjueg"],
    ["The Convo Couch",            RUMBLE,     "TheConvoCouch"           ],
    ["Ryan Matta",                 YOUTUBE,    "UCUBwBSeW51ZflGMPE-2kjwA"],
    ["The Litter Box",             RUMBLE,     "InTheLitterBox"          ],
    ["Evenge of the Cis",          RUMBLE,     "EvengeOfTheCis"          ],
    ["Kimberly Guilfoyle",         RUMBLE,     "KimberlyGuilfoyle"       ],
    ["DML",                        RUMBLE,     "DML"                     ],
    ["AE911Truth",                 YOUTUBE,    "UCL-c_zvZ3lhlU7NU1ikxgmQ"],
    ["DonaldJTrumpJr",             RUMBLE,     "DonaldJTrumpJr"          ],
]

# fmt: on
NETWORK_ORPHANED = [
    "Bill Maher",
    "Creel",  # Learn to code edition (TODO).
    "Bishop Larry Gaiters",
    "Lark Davis",
    "Hashoshi",
    "Coin Bureau",
    "Digital Asset News",
    "Dapp University",
    "DataDash",
    "Sheldon Evans",
    "Alex Becker",
    "JRNY Crypto",
    "Benjamin Cowen",
    "Preston Pysh",
    "Bankless",
    "Crypto Banter",
    "Altcoin Daily",
    "BitBoy Crypto",
    "99Bitcoins",
    "Crypto Dad",
    "DataDash",
]

NETWORK_POPULIST = [
    "Brietbart News",
    "Stew Peters",
    "Infowars",
    "Infowars Warroom",
    "BannonsWarRoom",
    "NextNewsNetwork",
]

NETWORK_CON_INC = [
    "JustTheNews",
    "Real America's Voice",
    "NewsmaxTV",
    "FoxNews",
    "OANN",
    "NTD",
    "Sean Hannity",
]

NETWORK_HEALTH = [
    "Dr. Sten Ekberg",
    "Dr. Darren Schmidt, DC",
    "Dr. Mercola",
    "Robert Scott Bell",
    "Dr. John Campbel",
    "Dr. Paul Thomas Md",
    "Thomas DeLauer",
    "MotivationalDoc",
    "Children's Health Defense",
    "Dr. David Jockers",
    "Dr. Eric Berg",
    "Jerry Brainum",
    "Dr. Philip Oubre, MD",
    "Dr Brad Stanfield",
    "Ford Brewer MD MPH",
    "Dr. Rhonda Patrick",
    "Dr. Mark Hyman, MD",
    "Dr Sherri Tenpenny",
    "The Highwire with Dell Big Tree",
]

NETWORK_INDEPENDENT = [
    "DonaldJTrumpJr",
    "AE911Truth",
    "DML",
    "The Litter Box",
    "Evenge of the Cis",
    "Kimberly Guilfoyle",
    "Ryan Matta",
    "The Convo Couch",
    "The Real News Network",
    "Conversations That Matter",
    "Know More News",
    "AlisonMorrow",
    "Project Veritas Action",
    "Jim Breuer",
    "Isaac Smith",
    "Titus Smith",
    "Jason Bermas",
    "BraveTV",
    "Union of the Unwanted",
    "Ganzalo Lira",
    "RED PILL PORTAL",
    "Brittany Venti",
    "Sivaady",
    "Matt Gaetz",
    "Canadian Prepper",
    "Macroaggressions",
    "Russell Brand",
    "Liberal Hivemind",
    "Patrick Lancaster",
    "American Media Periscope",
    "And We Know",
    "Lawyers' Committee for 9/11 Inquiry",
    "JSlayUSA",
    "Thrivetime Show",
    "Richard Grove",
    "Kevin's Corner",
    "The United Spot",
    "Peak Prosperity",
    "Sean Morgan Report",
    "King Peter the Virile",
    "Full Disclosure",
    "Godspeak",
    "Dnajlion7",
    "Medical Medium",
    "Monkey Werx",
    "America Floats",
    "The Ripple Effect",
    "Conservative Daily",
    "Mr Truth Bomb",
    "And We Know",
    "On The Fringe",
    "Two Mikes",
    "Jeff Dornik Show",
    "Jeremy Herrell",
    "Sarah Corriher",
    "Cooper Stuff",
    "Neil Johnson",
    "Nick Moseder",
    "Ivory Hecker",
    "The Alpha Warrior Show",
    "Clif High",
    "TRUreporting",
    "Red Voice Media",
    "Citizen Media News",
    "Woke Societies",
    "Rekieta Law",
    "JD Rucker Show",
    "Monica Matthews",
    "Gavin McInnes",
    "Kim Iverson",
    "George Galloway",
    "Breaking Points",
    "Philip DeFranco",
    "Mel K Show",
    "Michael Knowles",
    "Ben Shapiro",
    "Dana Loesch",
    "Joe Rogan",
    "Alpa Soni",
    "Nicholas Veniamin",
    "Viva Frei",
    "Glen Greenwald",
    "Roosh V",
    "Academy of Ideas",
    "After Skool",
    "April Moss",
    "Pete Santilli Interviews",
    "The John Birch Society",
    "KanekoaTheGreat",
    "Behizy",
    "Donald Trump",
    "MarkLevinShow",
    "Glennbeck",
    "Charlie Kirk",
    "DineshDsouza",
    "Gothix",
    "Jovan Hutton Pulitzer",
    "Bret Weinstein",
    "ODD TV",
    "Man In America",
    "CDMedia",
    "Matt Walsh",
    "I,Hypocrite",
    "Slightly Offens*ve",
    "The Solari Report",
    "Dr. Steve Turley",
    "The Solari Report",
    "Dr. Steve Turley",
    "SCNR",
    "HighImpactFlix",
    "Lisa Haven",
    "The Conscious Resistance Network",
    "Rudy W. Guiliani",
    "Really Graceful",
    "The Crowhouse",
    "Lionel Nation",
    "CitizensInvestigativeReport",
    "Truthstream Media",
    "Caravan to Midnight",
    "Sam Tripoli",
    "Craig Mason",
    "Dan Bongino",
    "Natly Denise",
    "Declassified with Gina Shakespeare",
    "Earthfiles",
    "RichardMDolan",
    "Rebel News",
    "Sara Carter",
    "Journey to Truth",
    "The Salty Cracker",
    "Common Sense Soapbox",
    "FreedomToons",
    "WhatsHerFace",
    "Judicial Watch",
    "Dollar Vigilante",
    "Lauren Southern",
    "Sargon of Akkad",
    "Ryan Dawson",
    "PatriotStreetfighter",
    "PatrickByrne",
    "Memology 101",
    "Sydney Watson",
    "Akkad Daily",
    "Alen Dershowitz",
    "The Stoa",
    "America Uncovered",
    "China Unscripted",
    "laowhy86",
    "serpentza",
    "ADVChina",
    "NTDChinaUncensored",
    "Charisma on Command",
    "Styxhexenhammer666",
    "The Art of Improvement",
    "Whitney Cummings",
    "Other People's Lives",
    "The Christopher Wright Show",
    "Andy Ngo",
    "Dr Rashid A Buttar",
    "Fleccas Talks",
    "Press For Truth",
    "The School of Life",
    "Senator Ted Cruz",
    "Joe Scott",
    "Chris D'Elia",
    "1791",
    "Tim Ferriss",
    "Black Conservative Patriot",
    "Armored Skeptic",
    "Candace Owens",
    "The Truth Factory",
    "Tim Dillon Show",
    "Tim Dillon Show Clips",
    "The Tech Lead Show",
    "AdamcastIRL",
    "The John-Henry Westen Show",
    "Robert Gruler",
    "Matt Christiansen",
    "Chrissie Mayr",
    "Corey's Digs",
    "Jack Murphey Live",
    "Jordan B Peterson",
    "Anthony Brian Logan",
    "Doug Billings",
    "Theo Von",
    "Ryan Long",
    "Mr Obvious",
    "The Federalist",
    "TimPool",
    "Lex Fridman",
    "PowerfulJRE",
    "Paul Joseph Watson",
    "AwakenWithJP",
    "Thunderf00t",
    "Wearechange",
    "StevenCrowder",
    "Lauren Chen",
    "Rubin Report",
    "Rebel Wisdom",
    "Mark Dice",
    "RockingMrE",
    "TheQuartering",
    "The Jimmy Dore Show",
    "James Allsup",
    "Scott Adams",
    "Timcast IRL",
    "The Epoch Times News",
    "MrReagan",
    "The Last American Vagabond",
    "RSBN",
    "corbettreport",
    "Crossroads",
    "VALUETAINMENT",
    "American Thought Leaders",
    "PragerUniversity",
    "Liberty Hangout",
    "Lara Trump",
    "Maryam Henein",
    "DeceptionBytes",
    "Quite Frankly",
    "Ann Vandersteel | Steel Truth Medial",
    "SGTReport",
    "RedPill78",
    "Gateway Pundit",
    "ThePeteSantilliShow",
    "Computing Forever",
    "The Savvy Truth",
    "Spiro Skouras",
    "MouthyBuddha",
    "JordanSather",
    "EdgeofWonder",
    "VoxDay",
    "MillieWeaver",
    "Brendon O'Connel",
    "SarahWestall",
    "RichieFromBoston",
    "Dave Janda",
    "Thomas Wictor",
    "Black Pigeon Speaks",
    "The Truth About Cancer",
    "JustInformed Talk",
    "Dustin Nemos",
    "InPursuitOfTruth",
    "Stroppy",
    "DiamondandSilk",
    "IntheMatrixxx",
    "Health Ranger Report",
    "The Outer Light",
    "Ice Age Farmer",
    "Stefan Molyneux",
    "Matt Couch",
    "AmazingPolly",
    "An0maly",
    "Project Veritas",
    "Tracy Beanz",
    "Black Pilled",
]

NETWORK_CRYPTO = [
    "99Bitcoins",
    "Crypto Dad",
    "Alex Becker",
    "JRNY Crypto",
    "Lark Davis",
    "Hashoshi",
    "Coin Bureau",
    "Digital Asset News",
    "Dapp University",
    "DataDash",
    "Sheldon Evans",
    "JRNY Crypto",
    "Benjamin Cowen",
    "Preston Pysh",
    "Bankless",
    "Crypto Banter",
    "Altcoin Daily",
    "BitBoy Crypto",
]

NETWORK_MAP: Dict[str, Any] = {
    "independent": {
        "channel_data": NETWORK_INDEPENDENT,
        "max_days": 3,
    },
    "mainstream": {
        "channel_data": NETWORK_CON_INC,
        "max_days": 3,
    },
    "populist": {
        "channel_data": NETWORK_POPULIST,
        "max_days": 3,
    },
    "health": {
        "channel_data": NETWORK_HEALTH,
        "max_days": 7,
    },
    "crypto": {
        "channel_data": NETWORK_CRYPTO,
        "max_days": 3,
    },
}

TRENDING = set(NETWORK_CON_INC + NETWORK_INDEPENDENT + NETWORK_POPULIST)
